### ISSUE TITLE
Unable to build and install psycopg2 on Apple M1 chip with Python3.9

### ISSUE THREAD

**Issue by olamide226** [psycopg/psycopg2#1434]
**This is a bug tracker**
If you have a question, such as "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/). [✅](https://github.com/psycopg/psycopg2/issues/1208)
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)  [✅]
- [x] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)  [✅]
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.  [✅]

**Please complete the following information:**
- OS: macos 11.5.2 with M1 chip
- Psycopg version: psycopg2 >= 2.8.0
- Python version: python3.9.10
- PostgreSQL version: 14.2
- pip version: 22.0.4

using `pip install psycopg` I have tried installing various versions of psycopg2>=2.9.0 on my macOS M1 chip but zero success. 
I have followed this thread [here](https://github.com/psycopg/psycopg2/issues/1208) but had no success. 
I have installed the various required libraries like libpq, openssl but no success.
I have had some success building psycopg2 on python3.8 and tried porting the build to py3.9. But when I launch the app I get the infamous `Symbol not found: _PQbackendPID` error.
installing psycopg-binary did not work too which is expected.

I do not know what else to do. Any help is kindly appreciated. Here are the build errors I get
[clang_py39_build_error.txt](https://github.com/psycopg/psycopg2/files/8256087/clang_py39_build_error.txt)

**Comment by dvarrazzo** [comment]
```
      ld: library not found for -lssl
```

You don't have this library installed. Look about it in other tickets.

**Comment by olamide226** [comment]
Thanks. I fixed the issue with [this](https://stackoverflow.com/a/39244687/9181403)

**Comment by aweigor** [comment]
Issue still persists. If the problem occur, one need to link the library.
export LDFLAGS="-L$(brew --prefix openssl)/lib" 
export CPPFLAGS="-I$(brew --prefix openssl)/include"
